name: Merge to Main

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.github/workflows/must_merge.yml' # 이 파일은 workflow 파일의 이름에 따라 조정하세요.

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check if main branch
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            # .github/workflows 폴더는 제외
            if [[ "${GITHUB_WORKSPACE}" != *".github/workflows"* ]]; then
              echo "main branch에 직접 업로드 시도"
              exit 1
            fi
          fi

      - name: Checkout code
        uses: actions/checkout@v2
