name: Pylint

on:
  push:
    paths:
      - '**.py' # .py 파일이 변경되었을 때만 실행

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9.18"]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pylint
        pip install mxnet
        pip install --upgrade mxnet gluonnlp
        pip install pandas tqdm
        pip install sentencepiece
        pip install transformers
        pip install torch
        pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
